### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by eranimo** [freehaha/ng-classify-loader#1]
http://webpack.github.io/docs/how-to-write-a-loader.html#flag-itself-cacheable-if-possible

Simply add that line

**Comment by freehaha** [comment]
added. let me know if it's all good

**Comment by Arelav** [comment]
Not good.
"Module build failed: TypeError: this.casheable is not a function"
You have a type in a word cacheable.
Must be:
this.cacheable();

**Comment by coryschires** [comment]
+1 Please fix.

**Comment by cyberflohr** [comment]
+1 Please fix :-)

**Comment by freehaha** [comment]
that was a stupid mistake my me =p, please let me know if this fixes it. I wonder why i didn't just merge @eranimo 's PR.. must have missed it.. but appreciate the effort =)

**Comment by freehaha** [comment]
Closing. Also closing #2. Please reopen if there are problems.
